//============================================================================
// Name        : Hello.cpp
// Author      : HBB20
//============================================================================

//#include <iostream.h>
using namespace std;

int main() {
	int a,b,wait;
	cout << "This program will give you the summation of two values " << endl;
	cout << "Enter 1st value:";
	cin >>a;
	cout << "Enter 2nd value:";
	cin >>b;
	cout <<"Summation of "<<a<<" and "<<b<<" is "<<(a+b);
	cin >>wait;
	return 0;
}
